resources:
- name: source-code-from-github
  type: git
  source:
    uri: https://github.com/Nelima/Spring-hello.git
    branch: main

jobs:
- name: test-and-build
  public: true
  plan:
    - get: source-code-from-github
      trigger: true
  
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: java
            tag: 8
        inputs:
        - name: source-code-from-github
        outputs:
        - name: jar-file
        caches:
        - path: source-code-from-github/.m2
        run:
          path: ./source-code-from-github/ci/test-and-build.sh
    - put: s3-stored-jar
      params:
        file: jar-file/*.jar

- name: deploy-app-to-pcf
  public: true
  plan:
  - get: s3-stored-jar
    passed: [test-and-build]
    trigger: true
  - get: source-code-from-github
  - put: pcf-resource
    params:
      manifest: source-code-from-github/ci/manifest.yml